def print_args(args):
    def g(name, default=""):
        return getattr(args, name, default)

    print("Basic Config")
    print(f"  task_name: {g('task_name')}")
    print(f"  is_training: {g('is_training')}")
    print(f"  model_id: {g('model_id')}")
    print(f"  model: {g('model')}")
    print()

    print("Data Loader")
    print(f"  data: {g('data')}")
    print(f"  root_path: {g('root_path')}")
    print(f"  data_path: {g('data_path')}")
    print(f"  features: {g('features')}")
    print(f"  target: {g('target')}")
    print(f"  freq: {g('freq')}")
    print(f"  embed: {g('embed')}")
    print()

    print("Forecasting Task")
    print(f"  seq_len: {g('seq_len')}")
    print(f"  label_len: {g('label_len')}")
    print(f"  pred_len: {g('pred_len')}")
    print()

    print("Model Params")
    print(f"  enc_in: {g('enc_in')}")
    print(f"  c_out: {g('c_out')}")
    print(f"  d_model: {g('d_model')}")
    print(f"  n_heads: {g('n_heads')}")
    print(f"  e_layers: {g('e_layers')}")
    print(f"  d_ff: {g('d_ff')}")
    print(f"  factor: {g('factor')}")
    print(f"  dropout: {g('dropout')}")
    print(f"  activation: {g('activation')}")
    print(f"  patch_len: {g('patch_len')}")
    print(f"  use_norm: {g('use_norm')}")
    print()

    print("Train Params")
    print(f"  train_epochs: {g('train_epochs')}")
    print(f"  batch_size: {g('batch_size')}")
    print(f"  learning_rate: {g('learning_rate')}")
    print(f"  patience: {g('patience')}")
    print(f"  num_workers: {g('num_workers')}")
    print(f"  inverse_eval: {g('inverse_eval')}")
    print()

    print("GPU")
    print(f"  use_gpu: {g('use_gpu')}")
    print(f"  gpu: {g('gpu')}")
    print(f"  use_multi_gpu: {g('use_multi_gpu')}")
    print(f"  devices: {g('devices')}")
    print()
